### ISSUE TITLE
Votre checklist

### ISSUE THREAD

**Issue by pascalfares** [projets2017cl/vc#55]
- [ ] Je suis dans une team
- [ ] Je planifie mon travail en choisissant une issue tagé backlog
- [ ] Se regrouper par "issue" de backlog identique (par exemple l'équipe création bien, une autre suivi bien)
- [ ] créer votre propre projet ou (fork)
- [ ] démarrer le même processus dans vos propre projets 
- [ ] fusionner le travail des différents groupes

@projets2017cl/vc
